=== philipphermes/transfer-bundle/src/Resources/schema/transfer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="transfers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="transfer" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="property" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence/>
                                    <xs:attribute name="name" type="xs:string" use="required"/>
                                    <xs:attribute name="type" type="xs:string" use="required"/>
                                    <xs:attribute name="description" type="xs:string"/>
                                    <xs:attribute name="singular" type="xs:string"/>
                                    <xs:attribute name="isNullable" type="xs:boolean" default="false"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== philipphermes/transfer-bundle/tests/Data/User/Transfers/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<transfers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../../../../src/Resources/schema/transfer.xsd">

    <transfer name="User">
        <property name="email" type="string"/>
        <property name="password" type="string"/>
        <property name="addresses" type="Address[]" singular="address" isNullable="true"/>
    </transfer>

    <transfer name="Address" api="true">
        <property name="street" type="string"/>
        <property name="country" type="Country"/>
    </transfer>
</transfers>

=== philipphermes/transfer-bundle/tests/Data/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<transfers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../../src/Resources/schema/transfer.xsd">

    <transfer name="User">
        <property name="email" type="string"/>
        <property name="password" type="string"/>
        <property name="addresses" type="Address[]" singular="address" isNullable="true"/>
        <property name="roles" type="string[]" description="List of roles" isNullable="false"/>
    </transfer>

    <transfer name="Address">
        <property name="street" type="string"/>
    </transfer>
</transfers>
